title = "Raphaël Gass"
baseURL = 'https://gassraphael.github.io'

# This is what goes in <html lang="">
languageCode = 'en-us'

theme = "hugo-blog-awesome"

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable  Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = '' # G-MEASUREMENT_ID


# Enable emojis globally
enableEmoji = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="bio"
    name = 'Bio'
    url = '/bio/'
    weight = 30

[params]
  sitename = "Raphaël Gass"
  defaultColor = "light" # set default color mode: dark or light
  description = "Energy Process Engineer"
  mainSections = ['posts']

[params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Raphaël Gass"
  name = "Raphaël Gass"
  description = "Energy Process Engineer"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/gassraphael/"
